server:
  port: 8001

spring:
  application:
    name: cloud-payment-service
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource # 当前数据源操作类型
    driver-class-name: com.mysql.cj.jdbc.Driver # mysql驱动包
    url: jdbc:mysql://localhost:3306/cloud2_payment?useUnicode=true&characterEncoding=utf8 # 数据库名称
    username: root
    password: vv123456

mybatis:
  mapper-locations: classpath:mapper/*.xml # mapper映射文件
  type-aliases-package: com.htwy.springcloud.entities # 所有Entity别名类所在包

eureka:
  client:
    service-url:
      defaultZone: http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/,http://eureka7001.com:7001/eureka/
      #defaultZone: http://localhost:7001/eureka/ #客户端注册进eureka服务列表内
      #集群环境下注册进所有的eureka服务里
  instance:
    instance-id: payment8001 #主机名称，服务名称修改 默认是以ip和端口
    prefer-ip-address: true #访问路径可以现实IP地址