server:
  port: 80

spring:
  application:
    name: cloud-hystrix-order-service
eureka:
  client:
    register-with-eureka: false
    service-url:
      #defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/
      defaultZone: http://eureka7001.com:7001/eureka/

ribbon:
  #设置Openfeign读取及连接时间，默认是1秒，现设置成5秒
  ReadTimeout: 5000
  ConnectTimeout: 5000

feign:
  hystrix:
    enabled: true